### PR TITLE
Removed build settings and added JWT support

### PR DESCRIPTION
**Pull request by BeefyAdmiral**

### CODE REVIEW

**Comment by BeefyAdmiral** [comment]
JWT part added

**Comment by BeefyAdmiral** [comment]
Will wait for a review

**Review by tzjg7293 — APPROVED** [review]
Looks good!

**Comment by tzjg7293** [comment]
Thanks Anshul nice work!

**Comment by tzjg7293** [comment]
Will this JWT work for everything?

**Comment by tzjg7293** [comment]
If so I will look into implementing it for the Sharing page

**Pull request merged**
