### PR TITLE
Initial Backend setup

### PR DESCRIPTION
**Pull request by BeefyAdmiral**

### CODE REVIEW

**Review by paulgray01 — APPROVED** [review]
looks good

**Review by mitchelhussack — APPROVED** [review]
Looks great!

**Comment by paulgray01** [comment]
good

**Comment by mitchelhussack** [comment]
backend shit is cool!

**Comment by mitchelhussack** [comment]
I <3 barb

**Comment by BeefyAdmiral** [comment]
So true same here!

**Review by tzjg7293 — APPROVED** [review]
Wow looks so beautiful I can't believe it.

**Comment by BeefyAdmiral** [comment]
I love CAPSTOOOOOOOOONNNNNNNNNEEEEEEEEEE!

**Comment by tzjg7293** [comment]
Wowwwwwwwww

**Comment by tzjg7293** [comment]
New year new me 2023

**Comment by tzjg7293** [comment]
What a beautiful LIFE

**Pull request merged**
