### PR TITLE
Updated URL and Settings

### PR DESCRIPTION
**Pull request by BeefyAdmiral**

### CODE REVIEW

**Review by mitchelhussack — APPROVED** [review]
Perfect

**Review by tzjg7293 — APPROVED** [review]
Looks good thank you Anshul!

**Comment by tzjg7293** [comment]
Looks good

**Comment by tzjg7293** [comment]
THanks

**Comment by BeefyAdmiral** [comment]
lets goo

**Comment by BeefyAdmiral** [comment]
gj

**Pull request merged**
